[General]
; Generic bot name without a number suffix
BotName=discobot
; Continuum installation path
ContinuumDirPath=C:\Program Files (x86)\Continuum
; Special functions
SpecialFunctions=
; Discord Server Type
DiscordServerType=nexus
; Number of tabs to press when alt-tabing Subspace
AltTabCount=1
; Arenas to cyclically check for user activity
SwitchArenas=

[Discord]
; Token of the Discord server bot
; discobot
BotToken=
; Id of the Discord server for the Subspace chat link
ServerId=1381416054911139912
; Id of the Discord channel for propagation of chat messages from the current arena
ChatChannelId=1487914619216461935
; Id of the Discord channel for posting the player stats table
TableChannelId=1488959177551380530
; Ids of the Discord channels for propagation of chat messages from specific arenas
ChatChannelIds=
; Id of the Discord channel for propagation of practice spam messages
PracChannelId=
; Id of the public message icon
PublicMessageIconId=1488272133539762287
; Id of the team message icon
TeamMessageIconId=1488272134475350226
; Mentions in the format @<mention> that should be formatted and transmitted to Discord
MentionWhitelist=
; Mentions in the format @<mention> that must not be transmitted to Discord
MentionBlacklist=@everyone
; Flag to indicate whether a player list message shall be created and maintained by the bot
CreatePlayersMessage=1
; Flag to indicate whether the player list message shall be pinned after its initial creation
PinPlayersMessage=1
; Id of the channel to which the player list message is posted by the bot (if not defined, 
; the player list message is posted to the chat channel)
PlayersMessageChannelId=

[Recording]
; Number in seconds to pause showing stats the next time
StatsPauseInterval=300
; Number in seconds to wait for showing stats after a kill
StatsWaitInterval=10
; Number of seconds to keep showing the stats with full-screen chat after a kill
StatsShowInterval=12
; Number in seconds to keep showing the stats with full-screen chat after match end
EndStatsShowInterval=30
; Number in seconds for showing items
ItemsWaitInterval=180
; Negative offset for timeStamps of review marks
TimeStampOffset=-10
; Maximum number of review items per player
MaxReviewItems=3
